services:
  # --- API FastAPI ---
  - type: web
    name: tech-challenge-api
    env: python
    region: oregon 
    plan: free
    
    buildCommand: |
      pip install -r requirements.txt
      

      alembic upgrade head
      

      python scripts/create_admin.py
      

      python scripts/load_to_db.py

    startCommand: gunicorn api.main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:10000

    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: books-db 
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30

  # --- Dashboard Streamlit ---
  - type: web
    name: tech-challenge-dashboard
    env: python
    region: oregon
    plan: free
    rootDir: ./streamlit_dashboard
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard.py --server.port 10000 --server.address 0.0.0.0
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: books-db
          property: connectionString

# --- Banco de Dados Postgres ---
databases:
  - name: books-db
    region: oregon
    plan: free